version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Vérifier-distribution:
    desc: "Vérifier la distribution de l'hôte cible en utilisant gather_facts"
    cmds:
      - cd ~/ansible/DevOps-ansible && ansible all -m gather_facts --limit 192.168.222.45 | grep ansible_distribution

  02-Créer-fichier-install-update:
    desc: "Créer un fichier Ansible pour installer et mettre à jour les paquets"
    cmds:
      - touch ~/ansible/DevOps-ansible/install_update.yml
      - |
        echo "
        ---
        
        - hosts: all
          become: true
          tasks:

          - name: Mettre à jour le cache APT
            apt:
              update_cache: true
            when: ansible_distribution == \"Ubuntu\"  

          - name: Installer les mises à jour disponibles
            apt:
              upgrade: dist
            when: ansible_distribution == \"Ubuntu\"

          - name: Mettre à jour le cache DNF
            dnf:
              update_cache: true
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"8\"  

          - name: Installer les mises à jour disponibles
            dnf:
              upgrade: dist
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"8\"  
        " >> ~/ansible/DevOps-ansible/install_update.yml

  03-Exécuter-install-update:
    desc: "Exécuter le playbook Ansible pour mettre à jour et installer les paquets"
    cmds:
      - cd ~/ansible/DevOps-ansible && ansible-playbook --ask-become-pass install_update.yml

  04-Créer-fichier-install-apache:
    desc: "Créer un fichier Ansible pour installer apache"
    cmds:
      - touch ~/ansible/DevOps-ansible/install_apache.yml
      - |
        echo "
        ---

        - hosts: all
          become: true
          tasks:

          - name: Mettre à jour le cache APT
            apt:
              update_cache: true 
            when: ansible_distribution == \"Ubuntu\"   

          - name: Installer le paquet apache2
            apt:
              name: apache2
              state: latest
            when: ansible_distribution == \"Ubuntu\"   

          - name: Ajouter php support pour apache
            apt:
              name: libapache2-mod-php
              state: latest
            when: ansible_distribution == \"Ubuntu\"

          - name: Mettre à jour le cache DNF
            dnf:
              update_cache: true
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"8\"  

          - name: Installer le paquet httpd
            dnf:
              name: httpd
              state: latest
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"8\"  

          - name: Ajouter php support pour apache
            dnf:
              name: php
              state: latest
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"8\"      
        " >> ~/ansible/DevOps-ansible/install_apache.yml