
---

- hosts: all
  become: true
  tasks:

  - name: Installer apache2 et php packages pour Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent 
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: Installer le paquet httpd et Ajouter php support pour apache
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"

