
---

- hosts: all
  become: true
  tasks:

  - name: Mettre à jour le cache APT
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"  

  - name: Installer les mises à jour disponibles
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Mettre à jour le cache DNF
    dnf:
      update_cache: true
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8"  

  - name: Installer les mises à jour disponibles
    dnf:
      upgrade: dist
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8"  

