
---

- hosts: all
  become: true
  tasks:

  - name: Mettre à jour le cache APT
    apt:
      update_cache: true 
    when: ansible_distribution == "Ubuntu"

  - name: Mettre à jour tous les paquets CentOS
    dnf:
      update_cache: true
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"  

  - name: Installer le paquet httpd
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"  

  - name: Ajouter php support pour apache
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"      

