
---

- hosts: all
  become: true
  tasks:

  - name: installer les mises à jour (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"

  - name: installer les mises à jour (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes 
    when: ansible_distribution == "Ubuntu" 



- hosts: terraform_servers
  become: true
  tasks:        

  - name: Installer apache2 et php packages pour Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu" 

  - name: Installer le paquet httpd et Ajouter php support pour apache
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"


- hosts: monitoring_servers
  become: true
  tasks:

  - name: installer mariadb package (CentOS)
    tags: centos,monitor,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"  

  - name: installer mariadb package (Ubuntu)
    tags: monitor,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: absent
    when: ansible_distribution == "Ubuntu"     

