version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Vérifier-distribution:
    desc: "Vérifier la distribution de l'hôte cible en utilisant gather_facts"
    cmds:
      - cd ~/ansible/DevOps-ansible && ansible all -m gather_facts --limit 192.168.222.45 | grep ansible_distribution

  02-Créer-fichier-install-update:
    desc: "Créer un fichier Ansible pour installer et mettre à jour les paquets"
    cmds:
      - touch ~/ansible/DevOps-ansible/install_update.yml
      - |
        echo "
        ---
        
        - hosts: all
          become: true
          tasks:

          - name: Mettre à jour le cache APT et Installer les mises à jour disponibles
            apt:
              update_cache: yes
              upgrade: dist
            when: ansible_distribution == \"Ubuntu\"
              
          - name: Mettre à jour tous les paquets CentOS
            dnf:
              name: \"*\"
              state: latest
              update_cache: yes
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"9\" 
        " >> ~/ansible/DevOps-ansible/install_update.yml

  03-Exécuter-install-update:
    desc: "Exécuter le playbook Ansible pour mettre à jour et installer les paquets"
    cmds:
      - cd ~/ansible/DevOps-ansible && ansible-playbook --ask-become-pass install_update.yml

  04-Créer-fichier-install-apache:
    desc: "Créer un fichier Ansible pour installer apache"
    cmds:
      - touch ~/ansible/DevOps-ansible/install_apache.yml
      - |
        echo "
        ---

        - hosts: all
          become: true
          tasks:

          - name: Installer apache2 et php packages pour Ubuntu
            apt:
              name:
                - apache2
                - libapache2-mod-php
              state: latest  
              update_cache: yes
            when: ansible_distribution == \"Ubuntu\" 

          - name: Installer le paquet httpd et Ajouter php support pour apache
            dnf:
              name: 
                - httpd
                - php
              state: latest
              update_cache: yes
            when: ansible_distribution == \"CentOS\" and ansible_distribution_version == \"9\"
        " >> ~/ansible/DevOps-ansible/install_apache.yml

  05-Exécuter-install-apache:
    desc: "Exécuter le playbook Ansible pour mettre à jour et installer les paquets"
    cmds:
      - cd ~/ansible/DevOps-ansible && ansible-playbook --ask-become-pass install_apache.yml      